spring.application.name=studentmanagement
server.port=8080

# JDC Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Database creation and connection
spring.datasource.url=jdbc:postgresql://localhost:5432/studentmanagement
spring.datasource.username=prashamsheth
spring.datasource.password=seseragi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.packages-to-scan=com.cs157a.studentmanagement.model

# JWT properties
security.jwt.secret-key=945cb4d1d04540ea474f0deb133aecb8443353ff56ddd71e98e619276da5a565
# 1h in millisecond
security.jwt.expiration-time=3600000

# Enable logging for our filters
logging.level.com.cs157a.studentmanagement.controller.filters.StudentFilter=DEBUG
logging.level.com.cs157a.studentmanagement.controller.filters.InstructorFilter=DEBUG
logging.level.org.springframework.security=DEBUG

# Database population
spring.profiles.active=dev
spring.datasource.initialize=true
spring.sql.init.mode=always
spring.datasource.continue-on-error=true

# Change the password to whatever yours is
spring.datasource.username=postgres
spring.datasource.password=
